BASE_URL = "https://www.saucedemo.com/"
STANDARD_USER ="*[data-test=\"username\"]"
STANDARD_USER_KEYS ="standard_user"
LOCKED_OUT_USERNAME = "*[data-test=\"username\"]"
LOCKED_OUT_USERNAME_KEYS = "locked_out_user"
PASSWORD ="*[data-test=\"password\"]"
PASSWORD_KEYS ="secret_sauce"
LOGIN_BUTTON = "*[data-test=\"login-button\"]"
ERROR_ALERT = "*[data-test=\"error\"]"
LOCKED_OUT_ERROR_TEXT= "Epic sadface: Sorry, this user has been locked out."
INVENTORY_LIST = ".inventory_list"
INVENTORY_NAME_ITEM = ".inventory_list > .inventory_item"
INVENTORY_ITEM_NAME ="inventory_item_name"
INVENTORY_PRICE ="inventory_item_price"
PRODUCT_SORT_Z_TO_A = "/html/body/div/div/div/div[1]/div[2]/div[2]/span/select/option[2]"
PRODUCT_ORDER_BY_PRICE ="/html/body/div/div/div/div[1]/div[2]/div[2]/span/select/option[3]"
