# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from constants import *

class TestProductsCount():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_productsCount(self):
    self.driver.get(BASE_URL)
    self.driver.maximize_window()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, STANDARD_USER)))
    self.driver.find_element(By.CSS_SELECTOR, STANDARD_USER).send_keys(STANDARD_USER_KEYS)
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, PASSWORD)))
    self.driver.find_element(By.CSS_SELECTOR, PASSWORD).send_keys(PASSWORD_KEYS)
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, LOGIN_BUTTON)))
    self.driver.find_element(By.CSS_SELECTOR, LOGIN_BUTTON).click()
    ##products count check
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, INVENTORY_LIST)))
    elements =self.driver.find_elements(By.CSS_SELECTOR, INVENTORY_NAME_ITEM)
    assert len(elements) == 6

  
